### ISSUE TITLE
 No module named 'airflow_code_editor'

### ISSUE THREAD

**Issue by itaygalea** [ohadmata/simple-dag-editor#1]
Installed simple-dag-editor==0.1.0 on the host running Airflow and got error saying:
Broken plugin: [simple_dag_editor.simple_dag_editor]

**Comment by ohadmata** [comment]
@itaygalea what is the Airflow version?

**Comment by itaygalea** [comment]
Thanks for your response.
Airflow version: 1.10.12

**Comment by betaincao** [comment]
simple_dag_editor/app_builder_view.py

https://github.com/ohadmata/simple-dag-editor/blob/8c2a2c915e8c81f373486ff8da61dff25f419305/simple_dag_editor/app_builder_view.py#L79
here，replace 'airflow_code_editor' to 'simple_dag_editor'

**Comment by ohadmata** [comment]
solved.
